default["tor"]["socks-port"] = 9050
default["tor"]["socks-resolver-port"] = 9950
default["tor"]["control-port"] = 9051
default["tor"]["dns-port"] = 9053
default["tor"]["or-port"] = 9001
default["tor"]["dir-port"] = 9030
default["tor"]["control-password"] = "hF1oGnPn70x3u7w3" # doesn't really matter when the port is only accessible to VPN
default["tor"]["relay-bandwidth-rate"] = "128 KB"
default["tor"]["relay-bandwidth-burst"] = "256 KB"
