---
driver: vagrant

provisioner:
  name: chef_zero
  require_chef_omnibus: latest

platforms:
- name: debian-7
  driver:
    box: debian-7
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-7.2.0_chef-provisionerless.box
- name: debian-6.0
  driver:
    box: debian-6.0
    box_url: http://opscode-vm-bento.s3.amazonaws.com/vagrant/virtualbox/opscode_debian-6.0.8_chef-provisionerless.box

suites:
- name: default
  run_list:
<% ENV.fetch('RECIPES', 'default').split(/[ ,]+/).each do |recipe| %>
  - recipe[debian::<%= recipe %>]
<% end %>
- name: backports
  run_list:
  - recipe[debian::_backports_test]
